package com.ysferdgnn.postapp_api.api.database.models

import com.fasterxml.jackson.annotation.JsonIgnore
import io.swagger.annotations.ApiModel
import lombok.EqualsAndHashCode
import io.swagger.annotations.ApiModelProperty
import com.ysferdgnn.postapp_api.api.database.models.Users
import com.ysferdgnn.postapp_api.api.database.models.Post
import com.ysferdgnn.postapp_api.api.requests.CommentPostRequest
import lombok.Data
import javax.persistence.*

@Entity
@Table(name = "Comment")
@ApiModel(value = "Comment Model")
data class Comment   (
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    @ApiModelProperty(value = "Comment model autogenerated Id value")
     val id: Long? = null,

    @Column(name = "text", length = 500)
    @ApiModelProperty(value = "define post content")
     val text: String? = null,

    @ManyToOne(fetch = FetchType.LAZY, cascade = [CascadeType.ALL])
    @JoinColumn(name = "usersId", nullable = false)
     val users: Users? = null,

    @ManyToOne(fetch = FetchType.LAZY, cascade = [CascadeType.ALL])
    @JoinColumn(name = "postId", nullable = false)
    @JsonIgnore
     val post: Post? = null
)

