package com.ysferdgnn.postapp_api.api.database.models;


import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Table(name = "Likes")
@Getter
@Setter
@ApiModel(value = "Likes Model")
public class Likes implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    @ApiModelProperty(value = "Likes model autogenerated Id value")
    private Long id;

    @Column(name = "usersid",nullable = false)
    @ApiModelProperty(value = "User Id for describe who liked post")
    private Long usersId;

    @Column(name = "postid",nullable = false)
    @ApiModelProperty(value = "Post Id for describe which post liked")
    private Long postId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usersid",insertable = false,updatable = false,nullable = false)
    @JsonIgnore

    private Users users;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "postid",insertable = false,updatable = false,nullable = false)
    @JsonIgnore

    private Post post;
}
