package com.ysferdgnn.postapp_api.api.database.models

import com.fasterxml.jackson.annotation.JsonIgnore
import io.swagger.annotations.ApiModel
import io.swagger.annotations.ApiModelProperty
import com.ysferdgnn.postapp_api.api.database.models.Users
import com.ysferdgnn.postapp_api.api.database.models.Post
import java.io.Serializable
import javax.persistence.*

@Entity
@Table(name = "Likes")
@ApiModel(value = "Likes Model")
data class  Likes (
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    @ApiModelProperty(value = "Likes model autogenerated Id value")
     val id: Long? = null,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usersid", nullable = false)
    @JsonIgnore
     val users: Users?=null,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "postid", nullable = false)
    @JsonIgnore
     val post: Post?=null
)