package com.ysferdgnn.postapp_api.api.database.models

import io.swagger.annotations.ApiModel
import io.swagger.annotations.ApiModelProperty
import com.ysferdgnn.postapp_api.api.database.models.Post
import com.ysferdgnn.postapp_api.api.database.models.Likes
import java.io.Serializable
import java.sql.Timestamp
import javax.persistence.*

@Entity
@Table(name = "Users")
@ApiModel(value = "User Model", description = "Model")
data class Users  (
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    @ApiModelProperty(value = "User autogenerated id value")
    val Id: Long? = null,

    @Column(name = "name")
    @ApiModelProperty(value = "User 'name' value ")
    val name: String? = null,

    @Column(name = "username")
    @ApiModelProperty(value = "User 'username' value")
    val username: String? = null,

    @Column(name = "password")
    @ApiModelProperty(value = "User 'password' value")
    val password: String? = null,

    @Column(name = "createdAt")
    @ApiModelProperty(value = "User creation time ")
    val createdAt: Timestamp? = null,

    @Column(name = "updatedAt")
    @ApiModelProperty(value = "User updated time")
    val updatedAt: Timestamp? = null,

    @OneToMany(fetch = FetchType.LAZY, cascade = [CascadeType.ALL], mappedBy = "users")
    @ApiModelProperty(value = "usersCommentList")
    val comments: Set<Comment>? = null,

    @OneToMany(fetch = FetchType.LAZY, cascade = [CascadeType.ALL], mappedBy = "users")
    @ApiModelProperty(value = "usersCommentList")
    val posts: Set<Post>? = null,

    @OneToMany(fetch = FetchType.LAZY, cascade = [CascadeType.ALL], mappedBy = "users")
    @ApiModelProperty(value = "usersCommentList")
    val likes: Set<Likes>? = null
){
    constructor(
        id:Long?,
        name :String?,
        username:String?,
        password: String?,
        createdAt: Timestamp?,
        updatedAt: Timestamp?) :
            this(id,name,username,password,createdAt,updatedAt,null,null,null)
    constructor(username: String?,password: String?) : this(null,null,username,password,null,null,null,null,null)
}