package com.ysferdgnn.postapp_api.api.database.models;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.*;
import java.io.Serializable;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Set;

@Data
@Entity
@Table(name = "Users")
@ApiModel(value = "User Model",description = "Model")
public class Users implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    @ApiModelProperty(value = "User autogenerated id value")
    private Long Id;

    @Column(name = "name")
    @ApiModelProperty(value = "User 'name' value ")
    private String name;

    @Column(name = "username")
    @ApiModelProperty(value = "User 'username' value")
    private String username;

    @Column(name = "password")
    @ApiModelProperty(value = "User 'password' value")
    private String password;

    @Column(name = "createdAt")
    @ApiModelProperty(value = "User creation time ")
    private Timestamp createdAt;

    @Column(name = "updatedAt")
    @ApiModelProperty(value = "User updated time")
    private Timestamp updatedAt;

    @OneToMany(fetch = FetchType.LAZY,cascade = CascadeType.ALL,mappedBy = "users")
    @ApiModelProperty(value = "usersCommentList")
    private Set<Comment> comments;
}
